name: CI/CD Pipeline

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    name: Etapa de Build
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Generar cliente Prisma
        run: npx prisma generate

      - name: Validar compilación TypeScript
        run: npm run build

  docker:
    name: Etapa de Docker
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "Exportando credenciales AWS..."
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          export AWS_REGION=$AWS_REGION

      - name: Login a ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_URI: ${{ secrets.ECR_URI }}
        run: |
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          export AWS_REGION=$AWS_REGION

          echo "Autenticando con ECR..."
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin $ECR_URI

      - name: Asegurar existencia del repositorio ECR
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          export AWS_REGION=$AWS_REGION

          echo "Verificando si el repositorio existe..."
          aws ecr describe-repositories --repository-names examen2 --region $AWS_REGION || \
          aws ecr create-repository --repository-name examen2 --region $AWS_REGION

      - name: Construir y subir imagen Docker
        run: |
          REPO_NAME=${{ github.event.repository.name }}
          IMAGE_TAG=${REPO_NAME}-${{ github.run_number }}
          FULL_IMAGE_NAME=${{ secrets.ECR_URI }}:$IMAGE_TAG

          echo "Construyendo imagen Docker..."
          docker build -t $FULL_IMAGE_NAME .

          echo "Subiendo imagen a ECR..."
          docker push $FULL_IMAGE_NAME

  deploy:
    name: Etapa de Deploy
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Desplegar en EC2
        run: |
          REPO_NAME=${{ github.event.repository.name }}
          IMAGE_TAG=${REPO_NAME}-${{ github.run_number }}
          FULL_IMAGE_NAME=${{ secrets.ECR_URI }}:$IMAGE_TAG

          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_HOST }} "
            echo 'Logging into ECR...'
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
            docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}

            echo 'Pulling new image...'
            docker pull $FULL_IMAGE_NAME

            echo 'Stopping and removing old container...'
            docker stop catalogs || true
            docker rm catalogs || true

            echo 'Running new container...'
            docker run -d --name catalogs -p 80:3000 \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            $FULL_IMAGE_NAME
          "
